set ignorecase
set termguicolors
set smarttab
set cindent
set expandtab
set shiftwidth=2
set number
set relativenumber
set tabstop=2 softtabstop=2
set encoding=utf-8
set nohlsearch
set hidden
set noswapfile
set nobackup
set undodir=~/.vim/undodir
set undofile
set scrolloff=8
set signcolumn=yes
set guicursor=
