#!/usr/bin/env bash
alias asdf="setxkbmap us real-prog-dvorak"
alias aoeu="setxkbmap latam"

alias vim="nvim"
alias so="source ~/.zshrc"
alias zsh="nvim ~/.zshrc"
alias mart="cd /home/mart/"
alias vuepractice="cd /home/mart/practice/vue"
alias gopractice="cd /home/mart/practice/go"
alias init.vim="cd ~/.config/nvim && vim init.vim"
alias rustpractice="cd /home/mart/practice/rust"
alias tmux.conf="nvim ~/.tmux.conf"
alias books="ranger ~/pCloudDrive/Books"
alias kill="tmux kill-server"

alias gs="git status"
