#!/usr/bin/env bash

# Keyboard layout (Linux only - macOS uses System Settings)
if [[ "$(uname)" != "Darwin" ]]; then
  alias asdf="setxkbmap latam latin-real-prog-dvorak"
  alias aoeu="setxkbmap latam"
fi

alias vim="nvim"
alias so="source ~/.zshrc"
alias zsh="nvim ~/.zshrc"
alias init.vim="cd ~/.config/nvim"
alias tmux.conf="nvim ~/.tmux.conf"
alias kill="tmux kill-server"

alias gs="git status"

alias mng="python manage.py"
