# ------ general ------------------------------------
set -g prefix C-b

set -g escape-time 0
set -g base-index 1
set -g renumber-windows on
set -g mouse on
set -wg pane-base-index 1
set -g default-shell /bin/zsh
set -g default-terminal "tmux-256color"
set -ag terminal-overrides ",xterm-256color:RGB"

# rename-window
set -wg allow-rename off
set -wg automatic-rename off

set -wg mode-keys vi

# retain current path
bind c new-window -c "#{pane_current_path}"
bind % split-window -h -c "#{pane_current_path}"
bind '"' split-window -c "#{pane_current_path}"

# restart and edit
bind r source ~/.tmux.conf\; display "tmux config sourced"
bind e neww -n tmux-config "\${EDITOR:-vim} ~/.tmux.conf"

# ------ move around --------------------------------
bind h select-pane -L
bind l select-pane -R        # remove repeat, because of ls
bind j select-pane -D
bind k select-pane -U

# ------ border -------------------------------------

set -g pane-border-lines simple
set -g pane-active-border-style fg='#5eacd3'
set -g pane-border-style fg='#657B83'

# ------ copy and paste -------------------------------------
bind -T copy-mode-vi v send-keys -X begin-selection
if-shell "uname | grep -q Darwin" \
  "bind -T copy-mode-vi y send-keys -X copy-pipe-and-cancel 'pbcopy'" \
  "bind -T copy-mode-vi y send-keys -X copy-pipe-and-cancel 'xclip -in -selection clipboard'"


# ------ bindings -------------------------------------

# Real Programmers Dvorak: select windows with symbols (no shift needed)
# + [ { ( & = ) } ] * -> windows 1-9, 0
bind-key '+' select-window -t 1
bind-key '[' select-window -t 2
bind-key '{' select-window -t 3
bind-key '(' select-window -t 4
bind-key '&' select-window -t 5
bind-key '=' select-window -t 6
bind-key ')' select-window -t 7
bind-key '}' select-window -t 8
bind-key ']' select-window -t 9
bind-key '*' select-window -t 0


# ------ status theme -------------------------------
set -g status-style 'bg=#2e3440 fg=#5eacd3'

